spring:
  flyway:
    locations: classpath:db/migration/
    enabled: true
    clean-disabled: false
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
    username: dbadmin
    url: jdbc:postgresql://localhost:5432/testdb
    password: dbadmin


springdoc:
  swagger-ui:
    path: /swagger-ui.html


auth:
  secret-key: D9639D4680EAB16AAA1DD414A1BEA93D7C2455CB11C70AFEEC5DFA2CF6CDBEA72F9564BF0C52518B6153796F1D5F61A877F200BBAF8A0BBACA92AD901034BA8A
